Лямбды и функции высшего порядка
Romik4/myRepository pull request #10
Opened 2024-04-18 18:32 UTC by Romik4

2024-04-23 13:29 UTC, vrnvorona commented on app/src/main/java/kotlinFifthTask/fifthTask.kt
запускал код хоть?)

2024-04-23 13:31 UTC, vrnvorona commented on app/src/main/java/kotlinFifthTask/firstTask.kt
> +val newList = numbers.filter { it % 2 == 0 }.map { it * 2 }
```suggestion
val newList = numbers
    .filter { it % 2 == 0 }
    .map { it * 2 }
```
в котлине так принято делать такие операции

2024-04-23 13:33 UTC, vrnvorona commented on app/src/main/java/kotlinFifthTask/fourthTask.kt
> +fun stringSquare(a: Int, square: (Int) -> Int = { a * a }): String {
не оч понятно заче дефолтное значение, но в целом ок

2024-04-23 13:34 UTC, vrnvorona commented on app/src/main/java/kotlinFifthTask/ninthTask.kt
> +    println(calculate(2, 2, ::multiply))
сделай один пример без именованной функции и без лямбды-переменной, т.е. сделай лямбду in-place

2024-04-23 13:39 UTC, vrnvorona commented on app/src/main/java/kotlinFifthTask/tenthTask.kt
> +val maxNum = nums.fold(-45) {acc, i -> acc + i}
ты просто сделал отступ на сумму всех чисел в список, этот метод ничего не выссчитывает)
если поменять массив то ответ будет неверный

val min = numbers.reduce { acc, i -> if (i < acc) i else acc }

2024-04-23 13:39 UTC, vrnvorona requested changes
еще коммит почему то про ООП хотя тут лямбды...

2024-04-23 14:53 UTC, Romik4 commented on app/src/main/java/kotlinFifthTask/fifthTask.kt
да, запускал, но потом пробывал вносить изменения и видимо забыл перепроверить, что все работает.
Я хотел отсортировать массив по возрастанию, но у меня не получилось и я видимо удалил то, что не нужно было, и перед отправкой ПРа не проверил(

2024-04-23 14:53 UTC, Romik4 commented on app/src/main/java/kotlinFifthTask/firstTask.kt
> +val newList = numbers.filter { it % 2 == 0 }.map { it * 2 }
спасибо, поменяю

2024-04-23 17:09 UTC, Romik4 commented on app/src/main/java/kotlinFifthTask/ninthTask.kt
> +    println(calculate(2, 2, ::multiply))
я правильно понимаю, что нужно вместо, например, ::sum написать лямбду прямо в println()?
println(calculate(3, 4) { a, b -> a + b })

2024-04-24 07:35 UTC, vrnvorona commented on app/src/main/java/kotlinFifthTask/ninthTask.kt
> +    println(calculate(2, 2, ::multiply))
да

2024-04-24 07:43 UTC, vrnvorona approved these changes

2024-04-24 08:26 UTC, merged