Null-безопасность и обработка исключений
Romik4/myRepository pull request #11
Opened 2024-05-05 18:36 UTC by Romik4

2024-05-07 12:12 UTC, vrnvorona commented on app/src/main/java/kotlinSixthTask/fifthTask.kt
эксепшены кидаются когда происходит что-то плохое обычно, т.е. внутри блока try это должно произойти
а в catch надо обработать кастомный эксепшен

2024-05-07 12:12 UTC, vrnvorona commented on app/src/main/java/kotlinSixthTask/firstTask.kt
еще ?. если методы вызывать

2024-05-07 12:14 UTC, vrnvorona commented on app/src/main/java/kotlinSixthTask/thirdTask.kt
> +    println(s ?: "empty")
конечно да, но принт не показывает смену типа. лучше что-то типа `val a: String = s ?: ""`

2024-05-07 12:14 UTC, vrnvorona commented on app/src/main/java/kotlinSixthTask/thirdTask.kt
> +var s: String? = null
зачем-то var хотя не изменяемая переменная

2024-05-07 12:14 UTC, vrnvorona requested changes
задание с кастомной ошибкой поправить бы

2024-05-07 12:20 UTC, Romik4 commented on app/src/main/java/kotlinSixthTask/thirdTask.kt
> +    println(s ?: "empty")
делал исходя из условий задачи

2024-05-07 12:24 UTC, Romik4 commented on app/src/main/java/kotlinSixthTask/fifthTask.kt
т.е. я не могу прописать throw в блоке catch?
или тут ошибка в том, что я написал e: Exception, а надо было e: InvalidUserInputException, поскольку он кастомный?
Получается что-то типа того?
try {
        println("Введите целое число")
        val num: Int? = readlnOrNull()?.toInt()
        println(num)
    } catch (e: InvalidUserInputException) {
        println(e.message)
    }

2024-05-07 12:27 UTC, vrnvorona commented on app/src/main/java/kotlinSixthTask/fifthTask.kt
написать конечно можно, просто логика иная получается

предполагаемая логика - кинуть ошибку если что-то случится и обработать

текущая логика - что-то случалось и в рамках обработки ошибки мы кинули еще одну ошибку

это концептуально разная логика по смыслу

2024-05-07 12:27 UTC, vrnvorona commented on app/src/main/java/kotlinSixthTask/thirdTask.kt
> +    println(s ?: "empty")
так просто не видно типизацию т.к. принт хавает нулы

2024-05-07 12:29 UTC, Romik4 commented on app/src/main/java/kotlinSixthTask/fifthTask.kt
понял, подумаю, как переписать тогда, спасибо

2024-05-11 16:08 UTC, vrnvorona commented on app/src/main/java/kotlinSixthTask/fifthTask.kt
в целом лучше решение, но можно было просто кинуть ошибку if == null

2024-05-13 06:42 UTC, merged